import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { memo, useState, Children, Fragment, type ReactNode } from 'react'
import { Check, Copy, FileText, ExternalLink } from 'lucide-react'

// Resolve a knowledge-base .md reference to the path relative to the knowledge
// root that readKnowledge expects. Handles the three shapes the UI receives:
//   1. bare relative filename  -> "AI趋势文章.md" / "sub/AI.md"
//   2. relative knowledge path -> "knowledge/AI.md" / "workspace/knowledge/AI.md"
//   3. absolute container path -> "/opt/data/profiles/<id>/workspace/knowledge/AI.md"
// Case 3 is what hermes' write_file tool reports back (its `resolved_path`),
// so the model often echoes it verbatim in its reply — it must still be
// clickable. Without this, "对话产生的文件" links silently broke again once
// hermes started returning absolute paths.
function matchKbPath(text: string): string | null {
  const t = text.trim()
  const m =
    /\/knowledge\/([^\s"',)\]]+\.md)$/i.exec(t) ||
    /\/knowledge\/([^\s"',)\]]+\.md)/i.exec(t)
  if (m) return m[1]
  if (/^[\p{L}\d_. -]+(\/[\p{L}\d_. -]+)*\.md$/iu.test(t)) {
    return t.replace(/^(knowledge\/|\/knowledge\/)/, '')
  }
  return null
}

// Find absolute/relative knowledge paths embedded in plain prose (the model
// frequently writes e.g. "文件位置：/opt/data/profiles/main/workspace/knowledge/AI.md")
// so they can be turned into clickable links even outside inline code.
const KB_TEXT_PATH_RE = /(\/opt\/data\/profiles\/[^/\s"',)\]]+\/workspace)?\/knowledge\/[^\s"',)\]]+\.md/ig
// Workspace files generated by the agent (uploads, articles, reports, PDFs).
// Matches absolute container paths and the ~/.comworker shorthand.
const WORKSPACE_PATH_RE = /(?:~\/\.comworker|\/root\/\.comworker|\/opt\/data)\/profiles\/[^/\s"',)\\]]+\/workspace\/[^/\s"',)\\]]+|profiles\/[^/\s"',)\\]]+\/workspace\/[^/\s"',)\\]]+/gi

function matchWorkspacePath(text: string): string | null {
  const t = text.trim()
  const m = WORKSPACE_PATH_RE.exec(t)
  WORKSPACE_PATH_RE.lastIndex = 0
  if (m) return m[0]
  return null
}

interface LinkedSegment {
  text: string
  kbPath?: string
  workspacePath?: string
}

function splitLinkedText(text: string): LinkedSegment[] {
  const out: LinkedSegment[] = []
  let last = 0
  let m: RegExpExecArray | null
  WORKSPACE_PATH_RE.lastIndex = 0
  KB_TEXT_PATH_RE.lastIndex = 0

  // Collect all matches from both patterns, then merge them in order.
  const hits: Array<{ index: number; length: number; kbPath?: string; workspacePath?: string; full: string }> = []
  while ((m = WORKSPACE_PATH_RE.exec(text)) !== null) {
    hits.push({ index: m.index, length: m[0].length, workspacePath: m[0], full: m[0] })
  }
  while ((m = KB_TEXT_PATH_RE.exec(text)) !== null) {
    const full = m[0]
    const kbPath = full.slice(full.lastIndexOf('/knowledge/') + '/knowledge/'.length)
    hits.push({ index: m.index, length: full.length, kbPath, full })
  }
  hits.sort((a, b) => a.index - b.index)

  for (const hit of hits) {
    // Skip overlaps: if the next hit starts inside the previous one, ignore it.
    if (hit.index < last) continue
    if (hit.index > last) {
      out.push({ text: text.slice(last, hit.index) })
    }
    out.push({ text: hit.full, kbPath: hit.kbPath, workspacePath: hit.workspacePath })
    last = hit.index + hit.length
  }
  if (last < text.length) {
    out.push({ text: text.slice(last) })
  }
  return out
}

function CodeBlock({ lang, code }: { lang: string; code: string }) {
  const [copied, setCopied] = useState(false)
  const handleCopy = () => {
    navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }
  return (
    <div className="group relative my-2 rounded-lg bg-slate-50 border border-light-border overflow-hidden">
      <div className="flex items-center justify-between px-3 py-1.5 bg-slate-100 border-b border-light-border">
        <span className="text-[10px] text-light-text-secondary uppercase tracking-wider">{lang || 'code'}</span>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1 text-[10px] text-light-text-secondary hover:text-light-text transition-colors"
        >
          {copied ? <><Check size={11} /> 已复制</> : <><Copy size={11} /> 复制</>}
        </button>
      </div>
      <pre className="overflow-x-auto p-3 text-xs leading-relaxed">
        <code>{code}</code>
      </pre>
    </div>
  )
}

function MarkdownContentImpl({
  content,
  className = '',
  onOpenKnowledgeFile,
  onOpenWorkspaceFile,
}: {
  content: string
  className?: string
  onOpenKnowledgeFile?: (kbPath: string) => void
  onOpenWorkspaceFile?: (path: string) => void
}) {
  // Linkify knowledge-base and workspace file paths that appear as plain text
  // (not wrapped in backticks) inside a paragraph/list/quote. Hermes often
  // echoes absolute container paths after writing a file, so these must be
  // clickable.
  const withLinkedText = (children: ReactNode): ReactNode => {
    const out: React.ReactNode[] = []
    Children.forEach(children, (child, i) => {
      if (typeof child !== 'string') {
        out.push(child)
        return
      }
      splitLinkedText(child).forEach((seg, j) => {
        if (seg.kbPath && onOpenKnowledgeFile) {
          out.push(
            <button
              key={`link-${i}-${j}`}
              type="button"
              onClick={() => onOpenKnowledgeFile(seg.kbPath as string)}
              className="inline-flex items-center gap-1 rounded bg-light-bg/80 px-1 py-0.5 text-xs text-accent-blue font-mono hover:underline"
              title={`打开知识库文件 ${seg.kbPath}`}
            >
              <FileText size={11} className="shrink-0" />
              {seg.text}
            </button>,
          )
        } else if (seg.workspacePath && onOpenWorkspaceFile) {
          out.push(
            <button
              key={`link-${i}-${j}`}
              type="button"
              onClick={() => onOpenWorkspaceFile(seg.workspacePath as string)}
              className="inline-flex items-center gap-1 rounded bg-light-bg/80 px-1 py-0.5 text-xs text-accent-blue font-mono hover:underline"
              title={`打开文件 ${seg.workspacePath}`}
            >
              <ExternalLink size={11} className="shrink-0" />
              {seg.text}
            </button>,
          )
        } else if (seg.text) {
          out.push(<Fragment key={`link-${i}-${j}`}>{seg.text}</Fragment>)
        }
      })
    })
    return out
  }
  return (
    <div className={`markdown-body text-sm leading-relaxed ${className}`}>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          // Let react-markdown handle pre/code keying natively (by node position).
          // Customizing `pre` to return <>{children}</> strips the pre's positional
          // key and causes "two children with same key" warnings for code blocks.
          // We only intercept `code` to detect fenced blocks and wrap them in
          // CodeBlock; react-markdown passes the same children to `pre` which we
          // leave as default.
          code({ className: cls, children, node, ...props }) {
            const isBlock = /language-/.test(cls || '') ||
              (typeof children === 'string' && children.includes('\n'))
            if (isBlock) {
              const match = /language-(\w+)/.exec(cls || '')
              const lang = match?.[1] || ''
              const code = String(children).replace(/\n$/, '')
              return <CodeBlock lang={lang} code={code} />
            }
            const text = typeof children === 'string' ? children : ''
            const trimmed = text.trim()
            const kbPath = onOpenKnowledgeFile ? matchKbPath(trimmed) : null
            if (kbPath) {
              return (
                <button
                  type="button"
                  onClick={() => onOpenKnowledgeFile(kbPath)}
                  className="inline-flex items-center gap-1 rounded bg-light-bg/80 px-1.5 py-0.5 text-xs text-accent-blue font-mono hover:underline"
                  title={`打开知识库文件 ${kbPath}`}
                >
                  <FileText size={11} className="shrink-0" />
                  {children}
                </button>
              )
            }
            const workspacePath = onOpenWorkspaceFile ? matchWorkspacePath(trimmed) : null
            if (workspacePath) {
              return (
                <button
                  type="button"
                  onClick={() => onOpenWorkspaceFile(workspacePath)}
                  className="inline-flex items-center gap-1 rounded bg-light-bg/80 px-1.5 py-0.5 text-xs text-accent-blue font-mono hover:underline"
                  title={`打开文件 ${workspacePath}`}
                >
                  <ExternalLink size={11} className="shrink-0" />
                  {children}
                </button>
              )
            }
            return (
              <code
                className="rounded bg-light-bg/80 px-1.5 py-0.5 text-xs text-accent-blue font-mono"
                {...props}
              >
                {children}
              </code>
            )
          },
          // Let react-markdown render the default <pre> wrapper. Customizing `pre`
          // to return <>{children}</> strips react-markdown's positional key from
          // the pre node, causing "two children with same key" warnings when
          // multiple fenced code blocks exist. By not overriding `pre` at all,
          // react-markdown keeps its native keying.
          // Note: `code` handler above still wraps fenced blocks in CodeBlock,
          // which renders its own <pre><code> inside a styled container.
          // The outer default <pre> from react-markdown will wrap CodeBlock,
          // which is harmless (CodeBlock is a div).
          p({ children }) {
            return <p className="mb-2 last:mb-0">{withLinkedText(children)}</p>
          },
          h1({ children }) { return <h1 className="text-lg font-bold mb-2 mt-3">{children}</h1> },
          h2({ children }) { return <h2 className="text-base font-bold mb-2 mt-3">{children}</h2> },
          h3({ children }) { return <h3 className="text-sm font-bold mb-1.5 mt-2">{children}</h3> },
          ul({ children }) { return <ul className="mb-2 ml-4 list-disc space-y-0.5 last:mb-0">{children}</ul> },
          ol({ children }) { return <ol className="mb-2 ml-4 list-decimal space-y-0.5 last:mb-0">{children}</ol> },
          li({ children }) { return <li className="text-sm">{withLinkedText(children)}</li> },
          blockquote({ children }) {
            return (
              <blockquote className="my-2 border-l-2 border-accent-blue/40 pl-3 text-light-text-secondary italic">
                {withLinkedText(children)}
              </blockquote>
            )
          },
          table({ children }) {
            return (
              <div className="my-2 overflow-x-auto rounded-lg border border-light-border">
                <table className="w-full text-xs">{children}</table>
              </div>
            )
          },
          thead({ children }) { return <thead className="bg-light-bg/50">{children}</thead> },
          th({ children }) { return <th className="px-3 py-1.5 text-left font-medium text-light-text-secondary border-b border-light-border">{children}</th> },
          td({ children }) { return <td className="px-3 py-1.5 border-b border-light-border/50">{children}</td> },
          a({ href, children }) {
            if (href && onOpenWorkspaceFile) {
              const ws = matchWorkspacePath(href)
              if (ws) {
                return (
                  <button
                    type="button"
                    onClick={() => onOpenWorkspaceFile(ws)}
                    className="inline-flex items-center gap-1 text-accent-blue hover:underline"
                    title={`打开文件 ${ws}`}
                  >
                    {children}
                    <ExternalLink size={11} className="shrink-0" />
                  </button>
                )
              }
            }
            if (href && onOpenKnowledgeFile) {
              const kb = matchKbPath(href)
              if (kb) {
                return (
                  <button
                    type="button"
                    onClick={() => onOpenKnowledgeFile(kb)}
                    className="inline-flex items-center gap-1 text-accent-blue hover:underline"
                    title={`打开知识库文件 ${kb}`}
                  >
                    {children}
                    <FileText size={11} className="shrink-0" />
                  </button>
                )
              }
            }
            return (
              <a href={href} target="_blank" rel="noreferrer" className="text-accent-blue hover:underline">
                {children}
              </a>
            )
          },
          hr() { return <hr className="my-3 border-light-border" /> },
          strong({ children }) { return <strong className="font-semibold">{children}</strong> },
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  )
}

const MarkdownContent = memo(MarkdownContentImpl)
export default MarkdownContent
